name: coverage

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Install llvm-tools-preview
        run: |
          rustup default nightly
          rustup component add llvm-tools-preview

      - name: Install grcov
        run: curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -

      - name: Generate code coverage
        run: |
          export RUSTFLAGS="-Cinstrument-coverage"
          export RUSTDOCFLAGS="-Cinstrument-coverage -Zunstable-options --persist-doctests target/debug/doctestbins"
          # cargo +nightly build --verbose --all
          LLVM_PROFILE_FILE="utils-lib-%p-%m.profraw" cargo +nightly test --verbose --all --features="coverage"

      - name: parse code coverage
        run: ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info

      - name: Upload to codecov.io
        run: bash <(curl -s https://codecov.io/bash) -f lcov.info
