name: Rust Doc check

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustdoc-check:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Rust stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rust-docs
    
    - name: Doc
      run: cargo doc --all --no-deps --document-private-items
