name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        profile: [test, release]
        exclude:
          - os: windows-latest
            profile: release
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install Rust stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
    
    - name: Run tests
      run: cargo test --profile ${{ matrix.profile }} --all --verbose --no-fail-fast
    
    - name: Run examples tests
      run: cargo test --profile ${{ matrix.profile }} --all --verbose --no-fail-fast --examples
    
    - name: Linter
      run: cargo clippy --profile ${{ matrix.profile }} --all --verbose --tests -- -D warnings
    